name: vit_gpt_flutter_api
description: "Collection of classes to save and connect to open ai resources"
version: 0.4.0
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.7.0
  flash: ^3.1.1
  flutter:
    sdk: flutter
  get_it: ^8.0.2
  just_audio: ^0.9.42
  ogg_opus_player: ^0.7.0
  path_provider: ^2.1.5
  record: ^5.2.0
  shared_preferences: ^2.3.3
  sqlite3: ^2.5.0
  vit_dart_extensions: ^2.7.0
  vit_gpt_dart_api: ^2.4.0
  vit_logger: ^2.1.1
  wakelock_plus: ^1.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
